logging:
  level:
    root: error
    me:
      sonam: debug
info:
  app:
    name: Springboot me.sonam.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

jwt:
  issuer: ${JWT_ISSUER}

spring:
  application:
    name: jwt-rest-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode:  ${DB_SSLMODE}

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka



permitpath:
  - path: /api/health/*
  - path: /jwts/accesstoken
    httpMethods: POST
  - path: /jwts/keyId
    httpMethods: POST
  - path: /jwts/publickeys/*
    httpMethods: GET
  - path: /jwts/hmac/*/*
    httpMethods: POST
