logging:
  level:
    root: error
    me:
      sonam: warn
info:
  app:
    name: Springboot me.sonam.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}