# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8081

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: jwt
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

eureka:
  client:
    enabled: false

jwt:
  issuer: https://www.sonam.cloud/jwts

# jwt-rest-service on port 8081 local server
#jwt-rest-service-public-key-id: http://localhost:8081/jwts/publickeys/{keyId}
jwt-service:
  root: http://localhost:${server.port}
  public-key-id: /jwts/publickeys/{keyId}

hmackeys:
  - app: '{"clientId":"authentication-rest-service","algorithm":"HmacMD5","secretKey":"51029d888xYA$","active":true, "isNew": true}'
  - app: '{"clientId":"account-rest-service","algorithm":"HmacMD5","secretKey":"51029d881xYA$","active":true, "isNew": true}'
  - app: '{"clientId":"user-rest-service","algorithm":"HmacMD5","secretKey":"51029d888AYA$","active":true, "isNew": true}'
  - app: '{"clientId":"application-rest-service","algorithm":"HmacMD5","secretKey":"51629d888xYA$","active":true, "isNew": true}'
