# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8081

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: jwt
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

eureka:
  client:
    enabled: false

jwt:
  issuer: https://www.sonam.cloud/jwts

# jwt-rest-service on port 8081 local server
JWT_REST_SERVICE: http://localhost:8081/jwts/publickeys/{keyId}