on:
  push:
    branches:
      - develop
      - main

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Export project name
        run: export PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2); echo $PROJECT_NAME

      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Open JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build Docker image and push to ghcr.io registry
        id: docker_build
        uses: docker/build-push-action@v3
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          context: .
          push: true
          tags: ghcr.io/sonamsamdupkhangsar/jwt-rest-service:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.K8CLUSTER_NAME }}

      - name: Deploy to k8 cluster
        run: |
          export TAG="latest@${{ steps.docker_build.outputs.digest }}"
          export PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2)
          helm repo add sonam https://sonamsamdupkhangsar.github.io/sonam-helm-chart/
          helm upgrade --install --timeout 5m0s \
            --set "image.repository=ghcr.io/sonamsamdupkhangsar/$PROJECT_NAME" \
            --set "image.tag=latest" \
            --set "project=$PROJECT_NAME" \
            --set "envs[0].name=JWT_SECRET" --set "envs[0].value=${{ secrets.JWT_SECRET }}" \
            --set "envs[1].name=JWT_ISSUER" --set "envs[1].value=${{ secrets.JWT_ISSUER }}" \
             $PROJECT_NAME \
            sonam/mychart -f values-backend.yaml --version 0.1.19 --namespace=backend

#        - name: Publish Pacts
#          run: mvn pact:verify -Dpactbrokerurl=${{ secrets.PACTBROKER_URL }} -Dpactbrokerusername=${{ secrets.PACTBROKER_USERNAME }} -Dpactbrokerpassword=${{ secrets.PACTBROKER_PASSWORD }}
